using System;

namespace Assets.Scripts.Games.NeighbourhoodActivity {
public enum Possibilities {

	BEHIND, BEHIND_STREET, LEFT, LEFT_STREET, RIGHT, RIGHT_STREET, BETWEEN, IN_FRONT, IN_FRONT_STREET,
	LEFT_SCHOOL_STREET, RIGHT_SCHOOL_STREET, BEHIND_SCHOOL, IN_FRONT_SCHOOL, IN_FRONT_SCHOOL_STREET
}
}
